development:
  adapter: postgresql
  encoding: unicode
  database: summer_tech_demo_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: summer_tech_demo_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: summer_tech_demo_production
  pool: 5